### ISSUE TITLE
error in module.js

### ISSUE THREAD

**Issue by danielnv18** [frontend-united/generator-drupal-theme#27]
Hi I was installing and testing the generetor

``` shell
npm install -g generator-drupal-theme
```

This is the output

```
> execSync@1.0.2 install /usr/local/lib/node_modules/generator-drupal-theme/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
generator-drupal-theme@0.1.6 /usr/local/lib/node_modules/generator-drupal-theme
├── rimraf@2.2.8
├── underscore.string@2.3.3
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── yosay@0.1.0 (pad-component@0.0.1, word-wrap@0.1.3, minimist@0.0.9)
├── execSync@1.0.2 (temp@0.5.1)
└── yeoman-generator@0.16.0 (dargs@0.1.0, isbinaryfile@2.0.4, diff@1.0.8, debug@0.7.4, class-extend@0.1.1, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, async@0.2.10, mkdirp@0.3.5, shelljs@0.2.6, iconv-lite@0.2.11, lodash@2.4.2, file-utils@0.1.5, glob@3.2.11, request@2.30.0, inquirer@0.4.1, cheerio@0.13.1, download@0.1.19)
```

and when I try to run the generator I get this

```
 yo drupal-theme
module.js:338
    throw err;
    ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-drupal-theme/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Any Ideas if I did something wrong?

**Comment by danielnv18** [comment]
Duplicated of #20 sorry
